node {
    stage('Checkout') {
        git branch: 'master', url: 'https://github.com/nanelle129/MSD-Auth.git'
    }
    
    stage('Gradle build') {
        sh 'gradle -b mcc-auth-api-template/build.gradle clean build'
    }
    
    stage('Gradle bootJar') {
        sh 'gradle -b mcc-auth-api-template/build.gradle bootJar'
    }
    
    stage('User Acceptance Test') {
		def response= input message: 'Is this build good to go?', 
		parameters: [choice(choices: 'Yes\nNo', 
		description: '', name: 'Pass')]
		
		if(response=="Yes") {
			stage('Deploy') {
			sh 'gradle build'
			}
		}
	}
}